### ISSUE TITLE
EBA Frontend API'deki değişiklikler nedeni ile çalışmıyor.

### ISSUE THREAD

**Issue by farukuruc** [caglarturali/eba_zoom_link#13]
Hocam Manjaro kullanıyorum. Tüm adımları yapıyorum lakin yeşil alandaki derse tıkladığımda link açılmıyor.

**Comment by farukuruc** [comment]
Hocam yeşil alanda link oluyor ama çalışmıyor.

**Comment by bytescreator** [comment]
@farukuruc Popup Ayarlarınızı kontrol ettiniz mi? hangi tarayıcıyı kullanıyorsunuz?

**Comment by farukuruc** [comment]
Hocam Chrome ve Fİrefox'ta da denedim olmadı.

**Comment by farukuruc** [comment]
Tampermonky ayarlarından yapmam gereken birşey var mı? Ayrıca Ubuntu'da çalışıyordu. Manjaro XFCE kullanıyorum.

**Comment by bytescreator** [comment]
Bende Arch linux xfce kullanıyorum bende çalışıyor. F12'den linklere bakabilir misiniz? Sağ tarafında event diye bir kutucuk olması lazım oradaki kodu atabilir misiniz?

**Comment by farukuruc** [comment]
Link derken EBA yı mı kastediyorsunuz ?

**Comment by bytescreator** [comment]
Tıkladığınız yeşil kısımdaki linkler

**Comment by farukuruc** [comment]
Orada ne sağ tık ne de sol tık çalışıyor. Canlı Dersler sayfasındayım.

**Comment by bytescreator** [comment]
Tamamdır, sanırım eba bişeyler değiştirmiş bakıyorum...

**Comment by farukuruc** [comment]
Asıl sorun şöyle hocam ben 11. Sınfım diğer yöntem işe yaramıyor. Kodu kopyala - yapıştır yöntemi.

**Comment by farukuruc** [comment]
![image](https://user-images.githubusercontent.com/62607789/93714542-0fe61c80-fb6c-11ea-871e-deafe7954670.png)
Sağ tarafta sanırım Error var.

**Comment by bytescreator** [comment]
baktım, eba sanırım sisteminde değişiklik yapmış. Ders başladımı sizin yoksa ders başlamadan mı gireceksiniz.
![Ekran görüntüsü_2020-09-20_18-05-30](https://user-images.githubusercontent.com/21954849/93714522-e6c58c00-fb6b-11ea-8cdf-d71b63b42cbd.png)
Bende de çalışmadı, ders başladıktan sonra deneyebilir misiniz? EBA değişiklik yapmış, önceden başlamadan token veriyordu.

**Comment by farukuruc** [comment]
Aynen hocam. Başlamadan girebiliyorduk. Yarın denerim artık bugün dersim yok.

**Comment by farukuruc** [comment]
Ders başlarken giriyorum hocam.

**Comment by bytescreator** [comment]
> ![image](https://user-images.githubusercontent.com/62607789/93714542-0fe61c80-fb6c-11ea-871e-deafe7954670.png)
> Sağ tarafta sanırım Error var.

Aynen, eba sisteminde değişiklik yapılmış bende de aynı sıkıntı, linkleri zamanı gelince aktive etmek lazım kodu değiştireyim ben... Bildirdiğiniz için teşekkür ederim.

**Comment by farukuruc** [comment]
Umarım sorunu en kısa sürede çözebilirsiniz hocam teşekkürler.

**Comment by farukuruc** [comment]
Hocam Tampermonky update yapmış. Girilebiliyor lakin başlayınca giriyor sanırım. Akşamki derse şimdi giremiyorum mesela sanırım öyle.

**Comment by bytescreator** [comment]
Denedim öğrenci kısmında çalışıyor.

Sadece EBA Api si değiştiğinden ötürü isteği 2dk önceden öncesine kadar atarsanız 500 dönüyor. 
Ayrıca biraz kurcalamışlar sanırım Tokensiz girilmiyor. getlivelessoninfo kısmında id ve password ile girebiliyordunuz artık sadece login kullanıcıları için ayarlamışlar meetingleri. 

Kafa karıştırmaması için bir uyarı ekledim tek değişiklik bu. Öğretmenlerde sıkıntı varmıdır bilmiyorum ancak onu da deneyeceğiz. 

Lacivert kısımda çalışıyor bu arada ben bir sıkıntı yaşamadım. Derse 2dk önce girilebiliyor en erken ondan çalışmadı muhtemelen.

**Comment by farukuruc** [comment]
Yani sanırım artık çalışıyor hocam teşekkürler.
