### ISSUE TITLE
Canlı derse katılmak istemiyorum. EBA'ya devam et butonu kaldırıldı.

### ISSUE THREAD

**Issue by DeadShowP** [caglarturali/eba_zoom_link#17]
Merhaba Canlı derse katılmak istemiyorum. EBA'ya devam et butonu kaldırıldı, haliyle derse gelen gri ekrandan katılmak zorunlu Sizce geri getirilebilir mi?

**Comment by bytescreator** [comment]
Pek düşünmüyorum, betiğin o ekranda bir sıkıntısı olmaması gerekmekte. Öğrenciler için EBA'ya erişim engelleniyor, akademik desteğe girmeyi deneyebilirsiniz 11. ya da 12. sınıf öğrencisi iseniz.

https://akademikdestek.eba.gov.tr/
