### ISSUE TITLE
Invalid Meeting ID Hatası alıyorum

### ISSUE THREAD

**Issue by BaranKrky** [caglarturali/eba_zoom_link#18]
![Ekran Görüntüsü (20)](https://user-images.githubusercontent.com/53481486/99937553-10bb4a80-2d77-11eb-974d-071fd048c001.png)

Bu hatayı neden alıyorum? Eba Frontend API'deki değişiklikler yüzünden mi, yoksa başka bi nedenden dolayı mı ?

**Comment by thebayram** [comment]
Aynı hatayı bugün almaya başladım.

**Comment by BaranKrky** [comment]
Peki EBA Frontend API'deki değişiklikler yüzünden olabilir mi ?

**Comment by BaranKrky** [comment]
![image](https://user-images.githubusercontent.com/53481486/99938184-52002a00-2d78-11eb-9207-e118104d6a5f.png)

**Comment by BaranKrky** [comment]
Bu daha önce yoktu yanılmıyorsam ?

**Comment by bytescreator** [comment]
Yarın ancak erişimim olacak EBA'ya ondan ötürü yarın bakacağım bakımda bişeyleri değiştirdiler muhtemelen.

**Comment by bytescreator** [comment]
Sorun eba ile ilgili, başlatma isteğini gönderdiğinizde geri size hangi tarayıcıyı kullandığınızı gönderiyor :facepalm:. Biraz bakayım token almanın bir yolu var mı diye.

**Comment by bytescreator** [comment]
@BaranKrky  Test Edemedim bunu ancak çalışıyor olması lazım

**Comment by BaranKrky** [comment]
Hemen deniyorum dersim vardı zaten

**Comment by BaranKrky** [comment]
![image](https://user-images.githubusercontent.com/53481486/100193617-30807900-2f05-11eb-998a-31b52b387780.png)
Aynı hatayı alıyorum. Çıkıp tekrar girmeyi denedim, betiği tekrar yükledim ama sonuç aynı.

**Comment by bytescreator** [comment]
tamam hata benden kaynaklı undefined i kaldırınca tokenden çalışması lazım bakıyorum

**Comment by BaranKrky** [comment]
Hemen bakıyorum

**Comment by BaranKrky** [comment]
![image](https://user-images.githubusercontent.com/53481486/100194469-ce287800-2f06-11eb-9841-b52db719148c.png)
Kusursuz bir biçimde çalışıyor.

**Comment by VentusForPc** [comment]
artık dersler 3 dakika erken başlıyor yardım edebilir misiniz
