### ISSUE TITLE
Öğretmen hesabında test edilmesi gerekli.

### ISSUE THREAD

**Issue by bytescreator** [caglarturali/eba_zoom_link#20]
EBA'nın yaptığı değişiklikler nedeniyle (detayı için #18 ve sh4dowb/eba-canli-ders-crossplatform#5) token alma mekanizmasını hem öğrenciler için hem de öğretmenler için değiştirdim (fbfb2d1af1b4202a6bd6ec49d0cf96c5f6a2cb3f), öğretmenler için düzgün çalıştığını doğrulayabilir misiniz?

**Comment by NurettinSelim** [comment]
çalışmıyor, zak tokeni 6. indekste bulunuyor çünkü :)

**Comment by bytescreator** [comment]
livelesson/nonce 'den dönen kısımda mı? örnek bişey atabilir misiniz?

**Comment by NurettinSelim** [comment]
https://github.com/sh4dowb/eba-canli-ders-crossplatform/blob/b4ee7bfbc984201fbd1ad4e616a5c91a6406fbf9/ogretmen.js#L64

`*****41kISwuomJMudnxmm3z2w13*****RiDVsl8iZk.Bg*****vNlMrZU5IQ1ZTe*****ZucXh*****K200bHBGV1*****5blY3SFB5VXhhb*****JKTFEvZVVJWE5nZTU2OVNxeHlJWkVKWFR*****OERKL0YxZ2ZnOE52MlkxaWlVAAAMM0NCQXV*****M3M9AAA|eyJhbG*****IUzI1NiIsInR5cCI6*****CJ9.eyJhcHBLZ*****J2TENjaGd2dzlW*****TJnWmJTVFZLVnIxMnFySldUNnRpZ*****JpYXQiOjE2MDYyOTgyMjAsImV4cCI6MTYw*****DIyMCwidG*****FeHAiOjE2MDg4OTAyMjB9.h*****Rlhu2OoHB1cNbJUuliv4yHyNUlzUvmP9keFaQ|85***7|1.2.3|İSİM S*******|1606****20000|eyJ6bV9za20iOiJ6bV9vMm0i*****GciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhd*****JjbGllbnQiLCJ1aWQiOiJ5Uj*****yZFNCZW55eVRBNlFnQjd3IiwiaXNzIjoid2ViIiw*****Ijo5OSwid2NkIjoidXMwMiIsImNsdCI6MCwic3RrIjoiTmQ3SnplOUt0dkk0*****VNoREt2a2FNVjhYalpVak5SRGtJTU54WE*****CZ1ZnZVdJdk5sTXJaVTVJUTFaVGVuWXJTMlp1Y1hoREt6VlNLMjA*****R1YxcHlhRVI1YmxZM1NGQjVWWGhoYjFOWlZFSktURkV2WlZWSldFNW5aVFUy*****GVIbEpXa1ZLV0ZSM1NVMHJPRVJLTDBZeFoyWm5PRTUyTWxreGFXbFZBQUFNTTBOQ1*****hVmxUTTNNOUFBUjFjekF5IiwiZXhwIjoxNjEzODE5MTE1LCJpYXQiOjE2MDYwNDMxMT*****pZCI6InZubGVyd3ZDUUt1NlNlc3o3Wk1DUlEiLCJjaWQiOiIifQ.0SgVke*****140YL42ojrU5A6xWy1*****YNy76PbEo|yR1W9Y2*****yyTA6*****|1606*****48*4`

**Comment by bytescreator** [comment]
Tamamdır 064657778942d6b231a919f599b1f33a62a8108d'da çözülmüş olması lazım, teşekkür ederim.
