### ISSUE TITLE
Cloudready - Chrome OS desteği

### ISSUE THREAD

**Issue by farukuruc** [caglarturali/eba_zoom_link#22]
Hocam kardeşimin bilgisayarına CloudReady - Chrome OS  yükleyeceğim. Betik çalışır mı? Zoom'un galiba desteği var.
Betik CloudReady - Chrome OS destekliyor mu?

**Comment by bytescreator** [comment]
@farukuruc betiğin herhangi bir sıkıntısı yok, tampermonkey kurulabilen her tarayıcıda  çalışabilir. Ancak Chrome OS'in zoom ile ilgili bazı sıkıntıları olabiliyor. 
https://github.com/sh4dowb/eba-canli-ders-crossplatform/issues/7#issuecomment-741111205
