### ISSUE TITLE
eba betik

### ISSUE THREAD

**Issue by VentusForPc** [caglarturali/eba_zoom_link#23]
eba artık yaklaşık 3 dakika erken başlıyor ve dersiniz başlamamış uyarısı alıyorum rica etsem bakabilir misiniz ?

**Comment by bytescreator** [comment]
Kusura bakmayin yeni gördüm, hangi sınıfsınız? Giriş yaparken https://ders.eba.gov.tr/ders/getlivelessoninfo kısmını gönderebilirseniz sürelere bakabilirim

**Comment by VentusForPc** [comment]
teşekkür ederim saatimin yanlış olduğunu fark ettim nası oldu anlamadım
