### ISSUE TITLE
Ders başlarken işe yaramıyor

### ISSUE THREAD

**Issue by Eren5960** [caglarturali/eba_zoom_link#4]
![image](https://user-images.githubusercontent.com/35738714/92226726-da73da80-eead-11ea-89b7-6e9267292785.png)

**Comment by caglarturali** [comment]
Başlarken mi başladıktan sonra mı? İşletim sistemi nedir? 
MacOS Catalina'da bu ekranı aşağıdaki seçenek ile geçtikten sonra betiğin oluşturduğu linkler üzerinden derse katılınabildiğini doğrulayabilirim.

**Comment by Eren5960** [comment]
İşletim sistemi: Deepin 20
Son bir kaç dakika kala bu sayfa açılıyor, devam et deyince yine aynı yer açılıyor (akademikdestek). buradan da normal eba ekranına erişimi engelliyor (403).

**Comment by rdkt60** [comment]
Sanırım bu konu ile ilgili bir güncelleme yapmışsınız, ama bugün denediğimde "Akademik Destek'e devam et" tuşuna bastığımda hiçbir ekran gelmedi, sanki betik yokmuş gibi Akademik Destek'e yönlendirdi. Chrome ve Firefox'ta denedim, eklentinin 0.2.4 sürümüydü (son sürüm galiba).

**Comment by bytescreator** [comment]
@rdkt60 Doğru, deneyememiştim en son pull'daki çalışır durumda(liveMiddleWare'da ebayı denemedim...)

Pull #10

**Comment by Eren5960** [comment]
Sorun çözülmüş

![image](https://user-images.githubusercontent.com/35738714/92720156-e3aced80-f36c-11ea-82d6-db53efabdbb9.png)
