### ISSUE TITLE
Öğretmen hesabında çalışmıyor.

### ISSUE THREAD

**Issue by biteker** [caglarturali/eba_zoom_link#5]
EBA Öğretmen hesabında çalışmayan uygulama. 
web servisin endpointini getstudentstudytime dan getteacherstudytime a değiştirdim ama zoom uygulaması açılmadı. Onun yerine zoom un sayfasına yöndendirip oturum açmamı istedi. Token bilgisi düzgün gelmedi sanırım. 
Öğretmen hesabında da çalışır hale getirirmek istiyorum. yardımcı olabilirseniz çok sevinirim. Kendim linux kullanıyorum çünkü eba canlı dersin linux sürümü çıkmadı ne yazıkki.

**Comment by caglarturali** [comment]
Hocam selamlar,
Öğretmen hesabı desteği sunabilmek için arkaplanda gidip gelen çağrıları inceleyebilmem lazım. Onun için de öğretmen hesabına ihtiyacım var ama erişimim yok, maalesef.

**Comment by bytescreator** [comment]
Merhabalar @biteker,

Öğretmenlerin kullandığı eba'da eba'ya geçmeden önceki canlı ders bildirimi çıkıyor mu?

**Comment by NurettinSelim** [comment]
![Ekran Resmi 2020-09-08 14 26 42](https://user-images.githubusercontent.com/30979744/92472370-08c12500-f1e2-11ea-8f77-d3b68940e3a6.jpg)
Yeni güncelleme ile son durum bu şekildedir.

**Comment by bytescreator** [comment]
@NurettinSelim Teşekkürler,
Başlatıldığı için mi çalışmadı yoksa kullanıcılar ile ilgili bir sıkıntı mı var?

**Comment by NurettinSelim** [comment]
Başlatılmadan önce denemiştim. Toplantı yöneticisi olarak görmüyor ne kadar token ile linke yönlendiriliyor olsak da.

**Comment by bytescreator** [comment]
Başlangıç saatinden önce mi girdiniz yoksa başlangıç saatinden sonra mı belki bundan ötürü olmuş olabilir.

**Comment by NurettinSelim** [comment]
@bytescreator Başlangıç saatinden 1 dakika önce denedim. Zoom kısmında bu problem değil istenilen zamanda başlatılabiliyor toplantı önceden planlanlanmış olsa da. EBA da token vermiş gibi gözüküyor.

**Comment by bytescreator** [comment]
@NurettinSelim aynen zoom istediğimiz saatte başlatmaya izin veriyor. 
Token dışında başka bir şey daha lazım o zaman...

zoom API dokümentasyonunda https://marketplace.zoom.us/docs/guides/auth/oauth#using-access-token 'da zoom api'sin de tokenlerin nasıl kullanılacağı yazıyor.

https://marketplace.zoom.us/docs/sdk/native-sdks/credentials#zak ve sanırım bunu kullanarak öğrencilere direk verilen zak tokenini almamız gerekli :facepalm:, normal token ile derse katılınabiliyor ancak sadece zak tokeni ile host olarak giriş yapılabiliyor.

https://marketplace.zoom.us/docs/sdk/native-sdks/user-login#comparing burada yazana göre ZAK tokeni giriş yapmamış kullanıcıları yetkilendirmek için kullanılıyor. Sanırım bunu alarak getlivelessoninfo 'dan dönen meetingStartUrl 'ye benzetmemiz gerek. 

Takip etmeniz mümkünse ebazoom: URI'sini nasıl çağırıldığına bakabilir misiniz? F12 (Konsol ya da Network) de ebazoom kurulu değilse unknown method olarak gözüküyor. Kurulu olduğunda F12:Network'de gözükmesi lazım.

**Comment by bytescreator** [comment]
@NurettinSelim Şunu fark ettim ki ZAK tokeninin içinde EBA'nın verdiği token de var ve bu ZAK tokeninin içindeki token sizin adres çubuğundakine çok benziyor, zoom garip bir uygulama olduğu için popup url'sini direk olarak `zoommtg://us02web.zoom.us/start?action=start&confno=${meetingId}&token=${token}....` olarak ayarlarsak belki girebilir. Ayrıca sizde kontrol ederseniz, öğretmenlere verilen tokende öğrenciler gibi `?pwd=` argumanı var mı? ve şu `ebazoom:` URI'sinin nasıl çağırıldığını görürsek daha rahat anlayabiliriz.

**Comment by NurettinSelim** [comment]
@bytescreator  macOS bir bilgisayarda denedim.
ebacanliders://meetingID=893*****579&token=916554*****1c3e6420c6*****a1fb12&username=********** &userSurname=K********&owner=true
böyle bir start kodu var.
ebazoom:'u alamadım windows bilgisayara geç açabildim dersi tekrar başlatamadım fakat dün denemiştim ebazoom:start:meetingId=x:token=y gibi bir yapı vardı. Bu yapıyı EBA'nın scriptini indirip ctrl+f yapıp aratırsanız bulabilirsiniz.


Eklentiyi kullanarak başlatmak istediğimde böyle bir linke yönlendirdi fakat token zak tokeni değil çünkü zak tokenini base64 decode ederseniz anlamlı birkaç parça göreceksiniz. Bunu decode ettiğim zaman aşırı anlamsız şeyler vardı. Zaten kıyaslayınca aşırı kısa kalıyor zak tokeni yanında.
https://us02web.zoom.us/s/893*****579?tk=-L6y1qLj2R03Cj*****ISyKmgIsbHAK_nkc7FlebXdI.BgVgeWIvN*****5IQ1ZTenYrS2ZucXhDM3loeTJVSEdwZThyaER5blY3SFB5VXlYVWVlbmJMZzFYSlAyVzRIY*****NxeHlJWkVKWFR3SU0rOERKL0YxZ2ZnOE52MlkxaWlVAAAMM0NCQXVvaVlTM3M9AAA

Örnek olarak başka bir dersin zak tokenli hali:
https://us02web.zoom.us/s/884*****018?zak=eyJ6bV9za20iOiJ6bV9vMm0iLCJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjbGllbnQiLC**********Vk5ka0hmdFNYeVMyM1FmM0xmMnVnIiwiaXNz*****2ViIiwic3R5Ijo5OSwid2NkIjoidX*****sImNsdCI6MCwic3RrIjoiNXQ2STA2c1FrN3R5NTFKeW**********cUxkeUk3YkNwOEoxb1ZUZHBwVS5CZ1ZnZVdJdk5sTXJaVTVJUTFaVGVuWXJTMlp1Y1hoRE1VOHJia1l4T0c1a0t5OXlhRVI1YmxZM1NGQjVWbE4wUVRGR1VIQ**********4ck1URllVMDB2ZGxOeGVIbEpXa1ZLV0ZSM1NVMHJPRVJLTDBZeFoyWm5PRTU**********FZBQUFNTTBOQ1FYVnZhVmxUTTNNOUFBUjFjekF5IiwiZXhwIjoxNjA3MzUyNzM1LCJpYXQiOjE1OTk1NzY3MzUsImFpZCI6IndGd2pjVkNTUWJ**********URQZUEiLCJjaWQiOiIifQ.kMZdikvsZfS1QcFAVJiP8DFGPdIXC4lX-cSSad0NMa8

**Comment by bytescreator** [comment]
@NurettinSelim Kusura bakmayın ancak müsait olabildim,

Kendi bilgisayarımda öğrenci hesabından aldığım zak tokeninin(Zak tokeni aslında bir JWT tokeni bilginiz olsun, https://jwt.io) içinden `stk` tokeni ile deneme yaptım, bende de aynı ekran çıktı :smile:, ya ZAK tokeni ve öğretmenlere dönen token(ya da komple istek cevabı) arasında fark var ya da belirttiğim dokumentasyonlardaki gibi token'i anahtar olarak kullanarak ZAK urlsini alacağız.

Merak ettiğim birkaç şey:

`ebacanliders://meetingID=893-----579&token=916554-----1c3e6420c6-----a1fb12&username=---------- &userSurname=K--------&owner=true`

URI'sinde token uzunluğu ne kadar? sabit 32 mi? ya da değişiyor mu?
Tamamı küçük harflerden mi oluşmakta?
Ders başlatımları arasında değişiyor mu?

Fark etmişsinizdir ebacanliders ve bize verilen zoom tokeni bayağı farklı. 
Kodu pek inceleyemedim (kullandığım her prettifier kitlenip kalıyor), ancak js script'ine bakarken fark ettim ki `getZoomJvtToken:function(e){return k(e)}` diye bir fonksiyon var ve API tokeni bu adresteki token olabilir. 

Eğer bu token, API tokeni ise tahminimce `https://api.zoom.us/`'e bu tokenle erişim sağlayabiliriz. EBA'nın zoom programı da ekstradan bu api'yi kullanıyor sanırım (öğrencilerde öğrenci bilgilerini sorgulamak için kullanıyor)

Ayrıca Öğretmen hesaplarında start url'sine istek yapıldığında öğrenci geri dönüşüne benzer bir istek mi geliyor? (belkide orada bize lazım olan bilgiler vardır, API ile uğraşmamıza gerek kalmaz)

Örnek öğrenci dönüşü (token sizin yorumunuzdaki gibidir)
`{"operationMessage":"success","operationCode":200,"success":true,"meeting":{"id":"eba_meeting_id","meetingId":"zoom_meeting_id","topic":"İNGİLİZCE","agenda":null,"type":2,"password":null,"creatorId":"mudur_id","teacherId":"ogretmen_id","startDate":1599816600000,"duration":30,"url":"https://us02web.zoom.us/w/zoom_meeting_id","token":"-L6y1qLj2R03Cj*****ISyKmgIsbHAK_nkc7FlebXdI.BgVgeWIvN*****5IQ1ZTenYrS2ZucXhDM3loeTJVSEdwZThyaER5blY3SFB5VXlYVWVlbmJMZzFYSlAyVzRIY*****NxeHlJWkVKWFR3SU0rOERKL0YxZ2ZnOE52MlkxaWlVAAAMM0NCQXVvaVlTM3M9AAA","owner":false,"deleted":false}}`

**Comment by NurettinSelim** [comment]
@bytescreator geçmişte de kaydetmiş olduğum bir response vardı. Aynen onda da 32 karakter.(Tire/Yıldız koyarken verilerde bozulma olmasın diye aynen karakter sayısı kadar koyuyorum. ) Elimdeki bir tane zak tokenini jwt'de ayırdım devamında stk'yı kopyaladım "."nın yeri betiğin verdiği tokendeki "."nın yeri ile birebir aynıydı fakat 6 karakter daha uzundu. acaba elimizdeki token stk mı? Ders başlatımları sırasında değişip değişmediğini bir dahaki derse kontrol etmem gerekecek. (Edebiyatçılara Fen Lisesinde çok ders yazmıyorlar :) ).

EBA scriptini gist'e yüklemeye çalıştım fakat 238 bin satırı ekleyemedim hata verdi :D
Bahsettiğiniz kısım neyi amaçlıyor ne yapıyor ben de hiç anlayamadım editör de hiç anlayamadı. Script dosyasında tek kullanım yeri sizin attığınız kısım başka hiçbir yerde kullanılmamış ama garip tek harf isimlendirmeler yüzünden kodu takip etmekte zorlanıyorum nereden geldiğini şaşırıyorum bi süre sonra.

```
fetch("https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//livelesson/instudytime/start", {
  "headers": {
    "accept": "json",
    "accept-language": "tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7",
    "content-type": "application/x-www-form-urlencoded",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site"
  },
  "referrer": "https://ders.eba.gov.tr/ders/proxy/VCollabPlayer_v0.0.687/index.html",
  "referrerPolicy": "no-referrer-when-downgrade",
  "body": "studytimeid=2fc75---d--19b---068d---29c1---0&tokentype=nonce&platform=",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
})
.then(res => res.json())
.then(data => console.log(data));

```
fetch kodunu kullanarak yaptığım request şöyle bir veri döndürmüştü.
```
{
    "operationMessage": "success",
    "operationCode": 200,
    "success": true,
    "meeting": {
        "id": "d0fc----c5ecaa31214e130f10d7----",
        "meetingId": "8363016----",
        "topic": "11ABC",
        "agenda": null,
        "type": 2,
        "password": null,
        "creatorId": "e8783----ab14a1f32b68----91bf860",
        "teacherId": "fd----a84ffa0691----ca2c6c----e8",
        "startDate": 1599557400000,
        "duration": 30,
        "url": "https://us02web.zoom.us/s/8363016----",
        "token": "a----5ff----ee770de----c9c85edf1",
        "owner": true,
        "deleted": false
    }
}
```

Hatta az önce kendim elle ebazoom:o=start&m=meeting_id&t=(üstteki response'daki token)
Şeklinde EBA uygulamasından dersi başlatmayı başardım. Bilgisayardaki tüm requestleri dinleyebileceğimiz bir uygulama YouTube'da çok önceden görmüştüm. Şimdi tekrar arıyorum fakat bulamadım. Belki EBA uygulamasını dinlersek bize biraz daha yol gösterebilir.

Yukarıda bir dahaki derse kontrol etmem gerek demiştim fakat fetch isteği sorunsuz bir şekilde çalıştı. Evet her seferinde token değişiyor.

**Comment by bytescreator** [comment]
@NurettinSelim Tamamdır, Uygulamanın verisini takip etmek için wireshark kullanabilirsiniz ancak TLS üstünden olduğu için okunmuyor, Windows'a geçip programı decompile etmeyi deneyeceğim. Oradan kurcalarım bende cevabınız için teşekkür ederim, detaylı olmuş, ayrıca bende eba'nın script'ini prettify edecek bi program bulamadım ya kendisi kitleniyor ya bilgisayarı kitliyor :sweat_smile:

**Comment by bytescreator** [comment]
@NurettinSelim Tekrar merhaba, 

Wireshark'ta TLS kullandığı için okuyamadım ancak kullandığı adreslerde api adresi yok, Denediğim decompiler'lar çalışmadı, Assembly den de pek bişey anlamadım. Bu yüzden SDK demolarına baktım

SDK demosuna(https://github.com/zoom/zoom-sdk-windows/blob/6295059767afa50e42ca8a59ce797a3001684c87/demo/sdk_demo_v2/LOGIN_sdk_login_UI.cpp#L191) ve birkaç microsoft sayfasına (https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins#sso-api-reference) baktıktan sonra sanırım bu token SSO tokeni gibi duruyor.

https://marketplace.zoom.us/docs/guides/guides/client-url-schemes#starting-a-meeting 'daki şema parametrelerinde token tipi `stype` parametresi ile belirlenebiliyor. Belirledikten sonra SSO tokenini vererek deneyebiliriz. SSO tokeni geçici tek kullanımlık bir token, hesaba giriş için kullanılıyor tahminimce bu sorunu çözecektir. 

Ayrıca EBA'da start ve join urlleri var, Öğrencilerde start url'sine istek yaparsanız zoom kullanıcı token(https://marketplace.zoom.us/docs/sdk/native-sdks/credentials#user-tokens )'i geliyor. Ancak join'e istek yaparsanız gönderdiğiniz gibi 32 karakterlik bir token geliyor, bu token sanırım SSO tokeni (pek emin olamadım, microsoft sayfasında ayrık şekilde 36 karakter ama birleştirince 32 oluyor, ayırmamız gerekebilir). Ayrıca ebazoom'u Zoom Tokeni ile çağırdığınızda program çalışmıyor. (muhtemelen SSO tokeni kullanması için hardcode edilmiş)

Yarın derslere SSO tokeni ile orijinal zoom programından girmeyi deneyeceğim. Bulduklarımı sizede buradan yazarım.
Siz de bahsettiğim join url'sini bulabilirmisiniz? Yarın derslere girerken bakacağım, öğretmenler ile öğrenciler aynı muhtemelen ancak emin olmak için bakmamız lazım.

**Comment by NurettinSelim** [comment]
@bytescreator 
```"https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//livelesson/instudytime/start"```
```"https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//livelesson/instudytime/join"```
bahsettiğiniz join ve start urlleri bunlar ise bende ikisi de aynı tarz 32 karakter olan tokeni döndürdüler.

**Comment by NurettinSelim** [comment]
@bytescreator öğretmen kısmında tek eksiğimiz sanki host user id gibi onu bulmaya çabalıyorum. https://marketplace.zoom.us/docs/guides/guides/client-url-schemes#starting-a-meeting
bu linkte zaten siz de okumuşsunuzdur token şifre değişmediği sürece değişmez diyor. Aynı şekilde betik ile yaptığım istekte uzun "."lı token tipinde her seferinde aynı tokeni verdi.

**Comment by bytescreator** [comment]
@NurettinSelim Aynen, o token kullanıcı tokeni şifre değişmediği sürece token sabit kalır. (custCreate ile yapıldığı için hesapların şifresi yok gerçi :smile:). Ancak o token non-login token olduğu için sadece o token ile meeting başlatılamıyor, ya zak tokeni alınması gerekli ya da SSO ile giriş yapılması lazım (https://marketplace.zoom.us/docs/sdk/native-sdks/user-login#comparing ). ZAK tokeni almak için API ile etkileşime girmek lazım onun içinde API anahtarı ve API secret'i lazım (ki wireshark taki yakalamaya göre hiç api.zoom.us DNS sorgusu yapmadı ve ip adresine bağlanmadı). SSO en mantıklı ve en mümkün yol gibi geldi bana. Zaten Zoom'un desteklediği 3 yetkilendirme şekli var

1. Email/Şifre
2. SSO
3. API çağrıları ile (JWT,OAuth ve API anahtarları)

Yarın denediğimizde belli olacak zaten, SSO tokeni dediğiniz gibi userid isteyebilir,istemeyebilir. Ancak host user id'sini bulmak için ya ZAK tokenine ya da API'ye ihtiyacınız var. SDK demosunda SSO logini için sadece token istiyordu ve ebazoom'da userID verilmiyor

**Comment by bytescreator** [comment]
@NurettinSelim Şimdi denedim, SSO token'i değilmiş YEĞITEK'in geliştirdiği garip bir token sanırım, tek kalan seçenek API'den ZAK tokeni almak, bir şekilde API ile etkileşime girmek gerekli. Siz bir sonuç elde edebildiniz mi?

eba'nin script.js' ini çözebilecek ve çökmeden okuyabileceğim bir editör bulayım en iyisi bir de orayı detaylıca inceleyelim. Belki api ile hiç uğraşmadan direk ZAK tokenini alabiliriz eba üstünden (Öğrencilere ZAK tokeni veriliyor, öğretmenler için de bulabiliriz belki)

**Comment by NurettinSelim** [comment]
@bytescreator ben de sabahtan beridir olabilecek her şekilde denedim fakat sonuç alamadım. Dediğiniz gibi YEGİTEK ile alakalı bir token sanırım. 

Script'i tarayıcının konsolunda açınca prettyprint yapayım mı diye sordu ve evet yap dedim. Chrome ve operada otomatik pretty yapıyor.

**Comment by NurettinSelim** [comment]
@bytescreator Nedendir bilemiyorum fakat mac EBA Canlı Ders uygulaması windows'tan farklı bir token kullanıyor. Yine tip olarak aynılar fakat fetch'de "platform=mac" diye belirtmek zorunda kaldım yoksa hiçbir şekilde EBA Canlı Ders uygulaması kullanarak dersi başlatamadım.

**Comment by bytescreator** [comment]
@NurettinSelim Mac ve Windows arasında fark olmaması lazım aslında ama yetkilendirme sistemindeki farklardan ötürü olabilir.

Ayrıca token'nin ne olduğunu şimdi fark ettim, `nonce` diye bir token türü varmış (https://en.wikipedia.org/wiki/Cryptographic_nonce ), yetkilendirme esnasında replay saldırılarını engellemek için kullanılıyormuş. start ya da join url'sine `tokentype="nonce"` olarak olarak ayarlarsanız nonce tokeni geliyor ve bu token genellikle rastgele oluyormuş, yani her istekte değişmesinin sebebi bu. Tabi ebazoom programının bununla ne yaptığı hakkında hiçbir fikrim yok.

nonce tokeni wikipedia sayfasına göre giriş bilgileri ile beraber bir hash fonksiyonundan geçerek yetkilendirme yapılıyor. Muhtemelen ebazoom ve ebacanliders içinde farklı işlemler yapılıyor. Wireshark'tan tekrar bakacağım. nonce tokenini orijinal zoom ile ilgili hiçbir arayüzde kullanamayız ebanın implementasyonu çünkü, API ve SDK dokumentasyonlarında hiç nonce tokeni ile yapılan birşey görmedim.

EBA bu nonce tokenini kullanarak kendi içinde bir yetkilendirme işlemi yapıyor muhtemelen. ebacanliders ve ebazoom 'un aynı token ile çalışmama sebebi bu olabilir.

Sadece meetingId'den userId bulunabiliyor hatta başlatma URL'si bile, API erişimine sahipseniz ki SDK'lar da(ebazoom) API anahtarı ve secret'i var, oradan start_url (https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meeting) ile meeting başlatılabiliyor (bildiğiniz zak tokeni olan url)

ZAK tokenini almak için iki yolumuz var
1. EBA üstünden inceleyerek
2. Eba canlı ders programı üstünden API için gerekli bilgileri alarak, ve bunu yapmak bayağı zor olacaktır.

ebazoom uygulamasına giden veriler ile bunu çözmemiz zor olacak gibi duruyor ve EXE dosyası da çözmemiz gerekiyor

> Belki api ile hiç uğraşmadan direk ZAK tokenini alabiliriz eba üstünden (Öğrencilere ZAK tokeni veriliyor, öğretmenler için de bulabiliriz belki)

Daha önceden sormuştum ama yine soracağım 

1. Öğretmenlerde öğrenciler gibi liveMiddleWare kısmı çıkıyor mu? Çıkıyorsa, öğrenci hesaplarındaki gibi https://ders.eba.gov.tr/ders/getlivelessoninfo adresinden gerekli ZAK tokenini alabiliriz. Çıkmıyorsada deneyin, canlı ders saatinde öğretmen tarafından belki erişilebilir.
2. ebacanlidersi 'i tokensiz başlatmayı denediniz mi hiç? Windows'ta direk arkaplanda hata raporu oluşturup gönderiyor. Yukarıda bahsettiğim ebanın kendi yetkilendirmesi ile ilgili olabilir.

User tokenleri ile meeting başlatılamıyor demiştik. Aynı token ile başka bilgisayardan derse katıldığınızda muhtemelen isminizde aynı çıkacaktır. ancak bu token'i sadece meetinglere katılırken kullanabiliyoruz. MacOS SDK'sını da inceledim, orada da api kullanıcıları için ZAK tokeni ile başlatıyor. Sadece ZAK tokeni ile öğretmen desteğini sağlayabileceğiz sanırım.

**Comment by NurettinSelim** [comment]
@bytescreator 
"EBA Canli Ders.exe"yi decompile ediyorum sonra hiç değiştirmeden tekrar compile etmeye çalışıyorum bir sürü hata alıyorum :)
exe'yi zaten çok okuyamıyorum c++ basit seviyede biliyorum + değişken isimlendirmesi namına hiçbir şey yok aynı scriptteki gibi. Büyük ihtimal bilinçli yapılıyordur.
1. Yol en mümkün hali gibi.
2. APİ'yi hazine gibi korumuşlardır, büyük ihtimal o kısımda zoom sdk ya da başka bir kütüphane yardımcı oluyordur. Kendileri eklememişlerdir ek bir şeyler.

1. Soruyu denemedim, en yakın ders Salı günü gözüküyor. Başka öğretmenler daha hızlı cevap verebilir sanırım bu soruya.
2. Denememiştim, denedim. Belki o tokeni kullanarak tekrar EBA'ya bir istek yapıyor olabilir oradan da bilgileri alıp derse giriyordur.

Yani user tokenleri sadece isim soyisim ve de kayıtlı oldukları meetinglerin listesini tutuyor.

**Comment by bytescreator** [comment]
@NurettinSelim aslında düzgün bir şekilde decompile olduysa güzel (en azından string değerleri), API key ve secretlerini aratabilirsiniz aslında ben pek başarılı olamadım decompiler konusunda :smile:. Müsaitseniz kodu burayada yükleyebilir misiniz?

Zoom sdk demosunda api anahtarları direk olarak programda "hardcoded" şekilde tutulmakta ebazoom'da da böyle ise oradan alabiliriz aslında.

**Comment by bytescreator** [comment]
@NurettinSelim Öğretmen hesaplarında canlı seminerler oluyormuş, scriptleri sonunda beautify etmeyi başardım, orada tokentype'i zak olarak tanımlıyor script. Ne döndüğünü bilmiyorum ama start url'sinde denemeye değer sanırım.

```
                    {
                    title: function(e) {
                        return L(e) ? vitamin.operations.PRODEV_LIVE_TRAINING_START : "PRODEV_LIVE_TRAINING_JOIN"
                    },
                    visibility: function(e) {
                        return b(e)
                    },
                    onClick: function(e) {
                        s.showPreloader();
                        var t = "nonce",
                            n = "";
                        E.isEbaUser() ? U.isMac && (n = "mac") : U.isMac && (t = "zak"), a.getStartLiveTraining(e.getID(), t, n).then(function(e) {
                            if (s.hidePreloader(), U.meeting = e.meeting, m.getOperatingSystem() === vitamin.system.browser.OPERATING_SYSTEM_WINDOWS) {
                                var t = U.meeting.owner ? "start" : "join",
                                    n = g.getZoomPath() + ":o=" + t + "&m=" + e.meeting.meetingId + "&t=" + U.meeting.token;
                                window.location.assign(n)
                            } else if (U.isMobile) U.meeting.userName = E.getUserName(), U.meeting.userSuname = w(E.getUserSurname()), U.meeting.serviceUrl = R.getFrontEndTeacherURL() + "/livelesson/nonce/", U.meeting.domain = "sebit.zoom.us", S.sendToMobile("zoomOperations", U.meeting);
                            else if (U.isMac)
                                if (E.isEbaUser()) {
                                    var i = "ebacanliders://meetingID=" + U.meeting.meetingId + "&token=" + U.meeting.token + "&username=" + U.meeting.userName + "&userSurname=" + w(U.meeting.userSuname) + "&owner=" + U.meeting.owner;
                                    window.location.assign(i)
                                } else s.openUrl(U.meeting.url, "_blank")
                        }, function(e) {
                            s.hidePreloader(), a.showAlertProxy(e)
                        })
                    }
```
> açıkçası çalışıp çalışmadığını bile bilmiyorum `U.isMobile` koşulundaki soyad tanımlamasına bakın :sweat_smile: 
```
   function h(n, i, o) {
        var c = e.defer();
        G && G.resolve(), G = s.getDeferred();
        var l = $.param({
                livetrainingId: n,
                tokentype: i,
                platform: o
            }),
            u = t({
                method: "POST",
                url: a.getNewFrontEndUrl() + "/livetraining/start",
                data: l,
                withCredentials: !0,
                timeout: G.promise,
                headers: {
                    "Content-Type": "application/x-www-form-urlencoded",
                    Accept: "json"
                }
            });
        return u.then(function(e) {
            r.checkResultException(e, !1, !0).getResult() ? c.resolve(e.data) : c.reject(e.data)
        }, function(e) {
            r.checkFailException(e).getResult() && c.reject({})
        }), c.promise
    }
```
`e.defer();` tokenin son halinin alınması için kullanıyor tahminim Ancak scriptte `e.defer();` vitamin'in angular uygulamasından fonksiyon argumanı olarak veriliyor ondan bulamadım. Script'in boyutu 6mb olduğu için debugger kullanmak genelde tarayıcıyı kitliyor :D

Bir de `https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//livelesson/nonce/${token}` var, nonce tokeni bildiğiniz şöyle yapılmış, `null|(isteğin gönderildiği zaman)` rastgele değil, zamanla değişiyor yani kesinlikle bir yetkilendirme için kullanılmıyor bu token. `e.defer()` den dönen `resolve` fonksiyonu ile bişeyler yapılıyor ama çözemedim daha.

```
await fetch("https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//livelesson/instudytime/start", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
        "Accept": "json",
        "Accept-Language": "tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7",
        "content-type": "application/x-www-form-urlencoded",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "referrer": "https://ders.eba.gov.tr/ders/proxy/VCollabPlayer_v0.0.692/index.html",
    "body": "studytimeid=(kendiniz bir ders id'si girin)&tokentype=zak&platform=",
    "method": "POST",
    "mode": "cors"
});
```

kendiniz bir id girerek dener misiniz? belki zak tokeni döner. Hiç denememiştik bunu, dönmez ise eba'yı daha derin araştırmamız ya da API bilgilerini programlardan çıkarmamız gerekli. Öğrencilerde `nonce` hariç her şeye kullanıcı tokeni'ni dönüyor. Öğretmenlerde farklıdır belki.

**Comment by NurettinSelim** [comment]
@bytescreator Dün tokentype=zak benim de aklıma geldi ve çalışacak gibi geliyor. İdarecilerden babama ders girmelerini isteyeceğim denemek için. Eski dersleri deneyince hata veriyor.

isMobile'ın kullandığı soyad sansürleme algoritması da güzeldi :)

Evet bir türlü debuggerlar yanıt vermiyor, dönüyor da dönüyor yuvarlak.

Ajax ile script yazdım. Birazdan olmadı bi müdürü arayayım.

**Comment by NurettinSelim** [comment]
```
$.ajax({
    url: "https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//studytime/getteacherstudytime",
    method: "POST",
    headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "json"
    },
    withCredentials: true,
    crossDomain: true,
    xhrFields: {
        withCredentials: true
    },
    dataType: "json",
    success: function (resp) {
        var result = resp.studyTimeList;
        var dersler = [];
        var promtText = "";
        var id = 1;
        for (var i in result) {
            dersler.push(result[i]);
            promtText = promtText + `${id.toString()}) ${result[i].classroom}. Sınıf ${result[i].title}\n`;
            id = id + 1;

        }
        if (dersler.length == 0) {
            alert("aktif ders yok");
            return;
        }
        var selectedDers = prompt("Seçim yapınız (sadece rakam girin):\n\n" + promtText);
        var ders = dersler[parseInt(selectedDers) - 1];
        $.ajax({
            url: "https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//livelesson/instudytime/start",
            method: "POST",
            headers: {
                "Content-Type": "application/x-www-form-urlencoded",
                "Accept": "json"
            },
            data: {
                "studytimeid": ders.id,
                "tokentype": "zak"
            },
            withCredentials: true,
            crossDomain: true,
            xhrFields: {
                withCredentials: true
            },
            dataType: "json",
            success: function (resp2) {
                window.location = `${resp2.meeting.url}?zak=${resp2.meeting.token}`;
            }
        });
    }
});
```

Keşke userscript yazmayı bilsem de yardımcı olabilsem, js dünyasına uzağım maalesef. Bu kodu kullanarak başlatabildim. Ellerinizden öper, kolay gelsin :)

**Comment by NurettinSelim** [comment]
@caglarturali hocam müsait olduğunuz zaman bakarsanız sevinirim.

**Comment by bytescreator** [comment]
@NurettinSelim Sağolun en başından bunu yapsaydık keşke, teşekkürler.

**Comment by NurettinSelim** [comment]
@bytescreator token türü nonce diyince bende çaktı şimşek fakat denemem mümkün olmamıştı.

**Comment by bytescreator** [comment]
@NurettinSelim tokentype parametresini görünce aklıma gelmişti, öğrencilerde çalışmıyor diye geçince boş yere uğraştırdım sizi, son hali ile düzelmiş olması gerekmekte bir sonraki derste deneyip kapatırsınız.

**Comment by bytescreator** [comment]
Tekrar merhaba,

@NurettinSelim @biteker inceleyebildiniz mi? sorunun çözülmüş olması gerekmekte. Ayrıca #13 deki sıkıntı öğretmen tarafınıda etkiliyor sanırım ona da bir çözüm ayarladım. Pek büyük bir şey değil zaten eba sadece zamanından önce token vermiyor artık ve derslerin ayarları değiştirilmiş tokensiz girilmiyor. Issue açılanı 17 gün olmuş :D kapatalım artık

**Comment by NurettinSelim** [comment]
@bytescreator Bende çalışmıştı, o zaman kapatacaktım fakat issue benim olmadığı için kapayamadım :)

**Comment by bytescreator** [comment]
Doğru, sonradan fark ettim @biteker 'in açtığını :D kapatıyorum sıkıntı olmaz tahminim yaşanırsa tekrar açılır zaten.

**Comment by biteker** [comment]
Çok teşekürler en kisa zamanda deneyecegim.
