### ISSUE TITLE
Script ana sayfada "Tamam" yazısının üstüne denk geliyor.

### ISSUE THREAD

**Issue by NurettinSelim** [caglarturali/eba_zoom_link#6]
![image](https://user-images.githubusercontent.com/30979744/92303341-8552ca00-ef7c-11ea-95f1-1e697ab9e848.png)
Resimde de görebileceğiniz şekilde tamam yazısına tıklamak mümkün değil. Daha önceden buna tıklamışlar için aşırı önemli değil fakat düzeltebilirseniz güzel olur.

**Comment by caglarturali** [comment]
Bu durumun farkındayım ama paneli farklı bir kenara taşımak veya boyutunu küçültmekten başka seçenek olmadığı ve bu seçenekler de kullanışlı olmadığı için böyle bırakmıştım. Boş bir alana tıklayınca mesaj kapanmıyor muydu?

**Comment by NurettinSelim** [comment]
Maalesef. Scripti kapatıp Tamam'a basmak da bir basit bir çözüm aslında.

**Comment by NurettinSelim** [comment]
https://iys.eba.gov.tr/ders/ContentSystem/getservertime
{"serverTime":1599306926854}
--------
https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//studytime/getteacherstudytime
https://paste.ubuntu.com/p/bxchXw8q8k/
----------------
bu şekilde iki tane request yapıyor. Bugünkü dersini zaten derslere
giremiyor diye işlememişler. "start" diyince ne döndüğünü maalesef
atamıyorum. İnşallah Salı günü ben de inceleyeceğim, size de yollarım.

**Comment by caglarturali** [comment]
> Maalesef. Scripti kapatıp Tamam'a basmak da bir basit bir çözüm aslında.

Bununla ilgileneceğim.

**Comment by caglarturali** [comment]
> Maalesef. Scripti kapatıp Tamam'a basmak da bir basit bir çözüm aslında.

Paneli 5 saniyeliğine gizleyen bir buton ekledim. :)
Betiği güncelleyip sonucu yazar mısın? Tampermonkey kontrol panelinden son güncelleme alanına tıklayarak güncelleyebilirsin.

**Comment by NurettinSelim** [comment]
Tamam, çok güzel olmuş. Teşekkürler.
