### ISSUE TITLE
Canlı Ders Vaktinde Derslere Giremiyorum (11. Sınıf)

### ISSUE THREAD

**Issue by NurettinSelim** [caglarturali/eba_zoom_link#9]
![image](https://user-images.githubusercontent.com/30979744/92376638-8e25d600-f10b-11ea-98fe-077f54781d30.png)
EBA Akademik Destek'e devam et diyince bu ekrana yönlendiriliyorum ve canlı dersler listelenmiyor.
![image](https://user-images.githubusercontent.com/30979744/92376283-093abc80-f10b-11ea-9910-1555eb9b64c0.png)
Buradan "EBA Sayfama Git" diyince de yine aynı geri sayım olan ekrana yönlendiriliyorum.
Yeni bir sekmeden "https://uygulama-ebaders.eba.gov.tr/ders/FrontEndService//livelesson/instudytime/start" url'ine istek yapmaya çalışınca da 403 döndürüyor.

**Comment by NurettinSelim** [comment]
https://ders.eba.gov.tr/ders/getlivelessoninfo
Canlı Ders geri sayımı ekranında bu url'e istek yaparak ders bilgilerini alıyor.
https://paste.ubuntu.com/p/82YgXR87rm/
örnek olarak dönen cevabı paylaşıyorum.

**Comment by bytescreator** [comment]
@NurettinSelim YEĞİTEK değişik şeyler yapmış, Aynı URL'yi kullan neden liveMiddleWare' a geçince ebayı blokluyorsun değil mi? https://ders.eba.gov.tr/ders/getlivelessoninfo adresini Fallback için eklemiştim ama deneyemediğimden pek çalışır durumda değilmiş.
Neyse, Çağrı Bey düzeltene kadar meetingId ve meetingPassword'u direk zoom'a girerek girebilirisiniz.

**Comment by NurettinSelim** [comment]
@bytescreator YEĞİTEK'te çalışan kişileri gerçekten merak etmeye başladım. Çalışmayan macOS programına güncelleme getirip durdular geçen dönem. Dayanamayıp geçen hafta CİMER'e yazdım hatayı. Sonunda düzeltildi. 1.0.11 sürümü çıkmış. macOS'da artık EBA Canlı Ders sorunsuz bir şekilde çalışıyor.
Öğretmenlere yardımcı olmak için co-host olarak girmeyi yeğlerim :))

**Comment by caglarturali** [comment]
Biraz işlerim vardı, ilgilenemedim kusura bakmayın. 
@bytescreator Son PR'ınızı merge ettim ama test etmedim. 

Anladığım kadarıyla şu noktadayız: 
- Öğrenci hesapları çalışıyor
- 11-12. sınıf hesapları sorun çıkarıyor
- Öğretmen hesaplarının durumu belirsiz (veya çalışmıyor)

**Comment by bytescreator** [comment]
@caglarturali Aynen 11. ve 12. sınıf hesapları bu merge ile çözülmüş olması gerekli, PR yorumlarındaki fotografta sıkıntı belli oluyordu, onu ayarladım.

Benim kendim kullandığımda sıkıntı yaşamadım. Bütün öğrencilerde çalışması gerekiyor.

Öğretmen Hesaplarının gerekli request'lerinide commit 1214723 bahsettiğim forum postundan aldım. Forum postu sadece chrome için çalışıyor ve öğretmen hesabımız olmadığı için deneyemedim. Kullanan hocalarımız issue ile bildirirler sanırım.

**Comment by NurettinSelim** [comment]
@caglarturali 
![Ekran Resmi 2020-09-08 14 26 42](https://user-images.githubusercontent.com/30979744/92471708-0f9b6800-f1e1-11ea-9a72-a99623ba3036.jpg)

Öğretmenlerin girebilmesi pek mümkün gözükmüyor.

**Comment by NurettinSelim** [comment]
![Ekran Resmi 2020-09-08 14 26 42](https://user-images.githubusercontent.com/30979744/92471832-44a7ba80-f1e1-11ea-9215-39d8ebe1a483.jpg)
Öğretmenleri girebilmesi pek mümkün gözükmüyor.
